SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
CREATE DATABASE `locker`;
USE `locker`;
CREATE TABLE `locker` (
  `id` int(11) NOT NULL,
  `name` text NOT NULL,
  `reference` text NOT NULL,
  `date` date DEFAULT NULL,
  `last_modified` timestamp NULL DEFAULT NULL,
  `IP` text DEFAULT NULL
) ENGINE=innodb DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
INSERT INTO `locker` (`id`, `name`, `reference`, `date`, `last_modified`, `IP`) VALUES
(1, '', '', '1970-01-01', NULL, NULL),
(2, '', '', '1970-01-01', NULL, NULL);
ALTER TABLE `locker`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
